apiVersion: manifests/v1beta1
metadata:
  name: uan
spec:
  charts:
  - name: cray-uan-install
    version: 1.2.2-20211119162716+7a73212
    namespace: services
    values:
      cray-import-config:
        catalog:
          image:
            tag: 1.3.1
        config_image:
          name: cray-uan-config
          tag: 0.3.2-20211119162716_7a73212
        import_job:
          CF_IMPORT_PRODUCT_VERSION: "@product_version@"
